#pragma once

// window
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define WINDOW_TITLE "JDGAME"

// Keys
#define KEYS_NUMBER 322
#define KEYS_PRESSED 0
#define KEYS_REPEAT 1
// Keys
#define KEYS_COUNT 5
#define KEY_UP 0
#define DEFAULT_KEY_UP SDLK_UP
#define KEY_DOWN 1
#define DEFAULT_KEY_DOWN SDLK_DOWN
#define KEY_LEFT 2
#define DEFAULT_KEY_LEFT SDLK_LEFT
#define KEY_RIGHT 3
#define DEFAULT_KEY_RIGHT SDLK_RIGHT
#define KEY_CANCEL 4
#define DEFAULT_KEY_CANCEL SDLK_ESCAPE

// Texture
#define TEXTURE_COUNT 1
#define TEXTURE_NONE -1
#define TEXTURE_JDG 0

// General
#define STATE_START_MENU 0
#define STATE_SETTINGS 1
#define STATE_GAME 2

// Button
#define BUTTON_INNER_PADDING_RATIO 0.15